[package]
name = "strunc"
version = "0.1.1"
edition = "2021"
authors = ["James Little <littleguy23@gmail.com>"]
description = "String truncation with suffixes"
license = "Apache-2.0"

[dependencies]
unicode-segmentation = "1.10.1"
